/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProductsProductIdImport } from './routes/products.$productId'
import { Route as BrandsBrandIdProductsImport } from './routes/brands.$brandId.products'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsProductIdRoute = ProductsProductIdImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRoute,
} as any)

const BrandsBrandIdProductsRoute = BrandsBrandIdProductsImport.update({
  id: '/brands/$brandId/products',
  path: '/brands/$brandId/products',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdImport
      parentRoute: typeof rootRoute
    }
    '/brands/$brandId/products': {
      id: '/brands/$brandId/products'
      path: '/brands/$brandId/products'
      fullPath: '/brands/$brandId/products'
      preLoaderRoute: typeof BrandsBrandIdProductsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/brands/$brandId/products': typeof BrandsBrandIdProductsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/brands/$brandId/products': typeof BrandsBrandIdProductsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/brands/$brandId/products': typeof BrandsBrandIdProductsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products/$productId' | '/brands/$brandId/products'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products/$productId' | '/brands/$brandId/products'
  id: '__root__' | '/' | '/products/$productId' | '/brands/$brandId/products'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  BrandsBrandIdProductsRoute: typeof BrandsBrandIdProductsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  BrandsBrandIdProductsRoute: BrandsBrandIdProductsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/products/$productId",
        "/brands/$brandId/products"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/products/$productId": {
      "filePath": "products.$productId.jsx"
    },
    "/brands/$brandId/products": {
      "filePath": "brands.$brandId.products.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
